# Generated by Django 2.0.7 on 2018-09-21 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kreiva', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
    ]
